apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/4a22dee8a67f66e5012729808de081d2f4d0e715/tasks/git-clone/git-clone-pr.yaml
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: release
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          volumeMounts:
          - mountPath: /home/jenkins
            name: workspace-volume
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - command:
          - jx step next-version --use-git-tag-only --tag
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: next-version
          resources: {}
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: release
          resources: {}
          script: |
            #!/bin/sh
            make release
        - env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: log-apply
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx admin log --sha-mode
        volumes:
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
