apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone-pr.yaml
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: pr-checks
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          volumeMounts:
          - mountPath: /home/jenkins
            name: workspace-volume
          - mountPath: /secrets/jx-boot
            name: jx-boot-secrets
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: verify-secrets
          resources: {}
          script: |
            #!/bin/sh
            jxl boot secrets export --dir=.
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: validate-git
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step git validate
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: create-helmfile
          resources: {}
          script: |
            #!/bin/sh
            jxl boot helmfile
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: lint-helmfile-system
          resources: {}
          script: |
            #!/bin/sh
            cd /workspace/source/system
            helmfile lint
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: lint-helmfile-apps
          resources: {}
          script: |
            #!/bin/sh
            cd /workspace/source/apps
            helmfile lint
        volumes:
        - emptyDir: {}
          name: jx-boot-secrets
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
