apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone.yaml
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: release
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - command:
          - jx step next-version --use-git-tag-only --tag
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: next-version
          resources: {}
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: verify-secrets
          resources: {}
          script: |
            #!/bin/sh
            jxl boot secrets export --dir=.
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: validate-git
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step git validate
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: verify-preinstall
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step verify preinstall --disable-verify-packages
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: generate-helmfile
          resources: {}
          script: |
            #!/bin/sh
            jxl boot helmfile
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: helmfile-system-diff
          resources: {}
          script: |
            #!/bin/sh
            cd /workspace/source/system
            helmfile diff
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: helmfile-system
          resources: {}
          script: |
            #!/bin/sh
            cd /workspace/source/system
            helmfile sync
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: verify-ingress
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step verify ingress
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: helm-label-repositories
          resources: {}
          script: |
            #!/bin/sh
            jxl boot step label repo
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: helmfile-apps-diff
          resources: {}
          script: |
            #!/bin/sh
            cd /workspace/source/apps
            helmfile diff
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: helmfile-apps
          resources: {}
          script: |
            #!/bin/sh
            cd /workspace/source/apps
            helmfile sync
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: git-creds
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step git credentials -o /builder/home/git/credentials
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: verify-jenkins-x-environment
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step verify env
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: install-pipelines
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step scheduler config apply --direct=true
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: helm-annotate
          resources: {}
          script: |
            #!/bin/sh
            jxl boot step annotate helm
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: verify-dns
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step verify dns --timeout 10m
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: update-webhooks
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx update webhooks --verbose --warn-on-fail
        - env:
          - name: JX_SECRETS_YAML
            value: /secrets/jx-boot/secrets.yaml
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: verify-installation
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step verify install --pod-wait-time 30m

  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
