apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: environment
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - command:
          - jx-kube-test
          - run
          - --chart-dir
          - charts
          image: gcr.io/jenkinsxio/jx-kube-test:0.0.11
          name: kubetest
          resources: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
