apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/git-clone/git-clone.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: next-version
      runAfter:
      - git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/terraform/release/next-version.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: jx-variables
      runAfter:
      - next-version
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/terraform/release/jx-variables.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: lint
      runAfter:
      - jx-variables
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/terraform/release/lint.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: changelog
      runAfter:
      - lint
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/terraform/release/changelog.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: promote
      runAfter:
      - changelog
      taskRef:
        params:
        - name: url
          value: https://github.com/jenkins-x/jx3-pipeline-catalog.git
        - name: revision
          value: versionStream
        - name: pathInRepo
          value: tasks/terraform/release/promote.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    workspaces:
    - name: pipeline-ws
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
  workspaces:
  - name: pipeline-ws
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 328761Ki
      status: {}
status: {}
